# Generated by Django 3.2.13 on 2022-09-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('sub_title', models.CharField(max_length=255, verbose_name='Подзаголовок')),
                ('button_text', models.CharField(max_length=100, verbose_name='Текст кнопки')),
                ('button_link', models.CharField(max_length=500, verbose_name='Ссылка кнопки')),
                ('sort', models.IntegerField(max_length=15, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'баннер',
                'verbose_name_plural': 'баннеры',
                'ordering': ['sort'],
            },
        ),
    ]
