# Generated by Django 3.2.13 on 2022-09-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image',
            field=models.ImageField(blank=True, upload_to='banner/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_link',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка кнопки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='button_text',
            field=models.CharField(blank=True, max_length=100, verbose_name='Текст кнопки'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='sort',
            field=models.IntegerField(default=100, max_length=15, verbose_name='Сортировка'),
        ),
    ]
