# Generated by Django 3.2.13 on 2022-09-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slider_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('icon', models.CharField(max_length=20, verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'тизер',
                'verbose_name_plural': 'тизеры',
                'ordering': ['title'],
            },
        ),
    ]
