# Generated by Django 3.2.13 on 2022-09-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaser',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Цвет'),
        ),
    ]
