# Generated by Django 3.2.13 on 2022-09-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_mainmenu_sort'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('path', models.CharField(max_length=500, null=True, verbose_name='URL')),
                ('sort', models.IntegerField(max_length=15, null=True, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'верхнее меню',
                'verbose_name_plural': 'верхнее меню',
                'ordering': ['sort'],
            },
        ),
    ]
