# Generated by Django 3.2.13 on 2022-09-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_alter_mainmenu_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='sort',
            field=models.IntegerField(null=True, verbose_name='Сортировка'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='sort',
            field=models.IntegerField(null=True, verbose_name='Сортировка'),
        ),
    ]
